# Generated by Django 3.0.5 on 2020-06-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
